In [1]:
import pandas as pd
import numpy as np
import os
os.environ['CUDA_VISIBLE_DEVICES'] = ""

all_data = pd.read_csv("../results/PETA_labels_pd.csv")
#all_data = all_data.set_index('0')
all_data

Unnamed: 0                                                  0    1  \
0               0  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
1               1  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
2               2  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
3               3  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
4               4  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
5               5  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
6               6  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
7               7  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
8               8  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
9               9  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
10             10  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
11             11  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
12             12  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
13             13  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
14             14  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
15             15  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
16             16  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
17             17  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18             18  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
19             19  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
20             20  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
21             21  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
22             22  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
23             23  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
24             24  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
25             25  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
26             26  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
27             27  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
28             28  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
29             29  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
...           ...                                                ...  ...   
18970       18970  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18971       18971  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18972       18972  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18973       18973  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18974       18974  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18975       18975  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18976       18976  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18977       18977  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18978       18978  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18979       18979  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18980       18980  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18981       18981  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18982       18982  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18983       18983  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18984       18984  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18985       18985  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18986       18986  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18987       18987  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18988       18988  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
18989       18989  /home/anhaoran/data/pedestrian_attributes_PETA...  0.0   
189

In [2]:
all_data_arr = np.asarray(all_data)
all_data_arr.shape

(19000, 67)

In [3]:
all_data_arr

array([[0,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/1246_b.png',
        0.0, ..., 5.0, 5.0, 1.0],
       [1,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/0726_b.png',
        0.0, ..., 1.0, 3.0, 5.0],
       [2,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/0023_a.png',
        0.0, ..., 1.0, 1.0, 1.0],
       ...,
       [18997,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/3DPeS/archive/11_985_FRAME_36_RGB.bmp',
        0.0, ..., 1.0, 5.0, 9.0],
       [18998,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/3DPeS/archive/4_237_FRAME_33_RGB.bmp',
        0.0, ..., 1.0, 1.0, 10.0],
       [18999,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/3DPeS/archive/202_80_FRAME_305_RGB.bmp',
        0.0, ..., 1.0, 5.0, 2.0]], dtype=object)

In [4]:
import random
random.shuffle(all_data_arr)
all_data_arr

array([[0,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/1246_b.png',
        0.0, ..., 5.0, 5.0, 1.0],
       [1,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/0726_b.png',
        0.0, ..., 1.0, 3.0, 5.0],
       [0,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/1246_b.png',
        0.0, ..., 5.0, 5.0, 1.0],
       ...,
       [17570,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/GRID/archive/0327_2_26220_169_19_69_143.jpeg',
        0.0, ..., 1.0, 1.0, 1.0],
       [5207,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/TownCentre/archive/58_1251.jpg',
        0.0, ..., 11.0, 2.0, 1.0],
       [8242,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/TownCentre/archive/22_376.jpg',
        0.0, ..., 1.0, 5.0, 1.0]], dtype=object)

In [5]:
random.shuffle(all_data_arr)
all_data_arr

array([[0,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/1246_b.png',
        0.0, ..., 5.0, 5.0, 1.0],
       [0,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/1246_b.png',
        0.0, ..., 5.0, 5.0, 1.0],
       [0,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/1246_b.png',
        0.0, ..., 5.0, 5.0, 1.0],
       ...,
       [538,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/PRID/archive/0372_a.png',
        0.0, ..., 1.0, 1.0, 1.0],
       [14820,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/CUHK/archive/3662.png',
        0.0, ..., 1.0, 5.0, 1.0],
       [4147,
        '/home/anhaoran/data/pedestrian_attributes_PETA/PETA/TownCentre/archive/46_1012.jpg',
        0.0, ..., 3.0, 5.0, 5.0]], dtype=object)

In [6]:
all_data_arr.shape

(19000, 67)

In [10]:
idxs = list(range(19000))
train_slice = random.sample(idxs, 9500)
for i in train_slice:
    idxs.remove(i)
val_slice = random.sample(idxs, 1900)
for i in val_slice:
    idxs.remove(i)
test_slice = idxs
print(len(train_slice), '\t', len(val_slice), '\t', len(test_slice))

9500 	 1900 	 7600


In [11]:
train = all_data_arr[train_slice]
val = all_data_arr[val_slice]
test = all_data_arr[test_slice]
print(train.shape)

(9500, 67)


In [12]:
new_all_data_arr = np.vstack((train, val, test))
new_all_data_arr.shape

(19000, 67)

In [13]:
attributes_pd = pd.DataFrame(new_all_data_arr[:, 1:])
attributes_pd

0  1  2  3  4  5  6  7   \
0      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
1      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
2      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  0  1  0   
3      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
4      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
5      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
6      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
7      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
8      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
9      /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
10     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  1   
11     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
12     /home/anhaoran/data/pedestrian_attributes_PETA...  0  1  0  0  0  0  0   
13     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
14     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
15     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  1  0  0   
16     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
17     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
18     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
19     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  1  0  0   
20     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
21     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
22     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  0  1  0   
23     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
24     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
25     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  0  1  0   
26     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
27     /home/anhaoran/data/pedestrian_attributes_PETA...  1  0  1  0  0  0  0   
28     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
29     /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
...                                                  ... .. .. .. .. .. .. ..   
18970  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
18971  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  1  0  0   
18972  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
18973  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
18974  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
18975  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
18976  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
18977  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  1  0  0   
18978  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
18979  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
18980  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
18981  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  1  0  0   
18982  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  1   
18983  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
18984  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  1  0  0  0   
18985  /home/anhaoran/data/pedestrian_attributes_PETA...  0  1  0  0  0  0  0   
18986  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  1  0  0  0  0   
18987  /home/anhaoran/data/pedestrian_attributes_PETA...  0  0  0  0  1  0  1   
1898

In [14]:
attributes_pd.to_csv("../results/PETA.csv")