In [1]:
import scipy.io as sio

!ls /home/anhaoran/data/pedestrian_attributes_PA-100K/annotation/
data = sio.loadmat('/home/anhaoran/data/pedestrian_attributes_PA-100K/annotation/annotation.mat')
data

annotation.mat	README.txt


{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Jul 26 13:11:29 2017',
 '__version__': '1.0',
 '__globals__': [],
 'attributes': array([[array(['Female'], dtype='<U6')],
        [array(['AgeOver60'], dtype='<U9')],
        [array(['Age18-60'], dtype='<U8')],
        [array(['AgeLess18'], dtype='<U9')],
        [array(['Front'], dtype='<U5')],
        [array(['Side'], dtype='<U4')],
        [array(['Back'], dtype='<U4')],
        [array(['Hat'], dtype='<U3')],
        [array(['Glasses'], dtype='<U7')],
        [array(['HandBag'], dtype='<U7')],
        [array(['ShoulderBag'], dtype='<U11')],
        [array(['Backpack'], dtype='<U8')],
        [array(['HoldObjectsInFront'], dtype='<U18')],
        [array(['ShortSleeve'], dtype='<U11')],
        [array(['LongSleeve'], dtype='<U10')],
        [array(['UpperStride'], dtype='<U11')],
        [array(['UpperLogo'], dtype='<U9')],
        [array(['UpperPlaid'], dtype='<U10')],
        [array(['UpperSplice'], dtype='<U11

In [2]:
idx = 'attributes'
#print(data[idx])
print(type(data[idx]))
print(data[idx].shape)
attributes_list = []
for i in range(len(data[idx])):
    attributes_list.append(data[idx][i][0][0])
print(attributes_list)

<class 'numpy.ndarray'>
(26, 1)
['Female', 'AgeOver60', 'Age18-60', 'AgeLess18', 'Front', 'Side', 'Back', 'Hat', 'Glasses', 'HandBag', 'ShoulderBag', 'Backpack', 'HoldObjectsInFront', 'ShortSleeve', 'LongSleeve', 'UpperStride', 'UpperLogo', 'UpperPlaid', 'UpperSplice', 'LowerStripe', 'LowerPattern', 'LongCoat', 'Trousers', 'Shorts', 'Skirt&Dress', 'boots']


In [3]:
idx = 'train_label'
#print(data[idx])
print(type(data[idx]))
print(data[idx].shape)
train_label = data[idx]
print(train_label)

<class 'numpy.ndarray'>
(80000, 26)
[[1 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


In [4]:
idx = 'train_images_name'
#print(data[idx])
print(type(data[idx]))
print(data[idx].shape)
#print(data[idx])
train_images_name = []
for i in range(len(data[idx])):
    train_images_name.append("/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/"+str(data[idx][i][0][0]))
    if i <= 10:
        print(train_images_name[i])
#print(train_images_name)

<class 'numpy.ndarray'>
(80000, 1)
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000001.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000002.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000003.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000004.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000005.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000006.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000007.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000008.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000009.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/000010.jpg
/home/anhaoran/data/pedestrian_attributes_PA-

In [10]:
idx = 'val_label'
#print(data[idx])
print(type(data[idx]))
print(data[idx].shape)
val_label = data[idx]
print(val_label)

idx = 'val_images_name'
#print(data[idx])
print(type(data[idx]))
print(data[idx].shape)
#print(data[idx])
val_images_name = []
for i in range(len(data[idx])):
    val_images_name.append("/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/"+str(data[idx][i][0][0]))
    if i <= 10:
        print(val_images_name[i])
#print(train_images_name)

<class 'numpy.ndarray'>
(10000, 26)
[[1 0 1 ... 0 1 0]
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [1 0 1 ... 1 0 0]
 [0 0 1 ... 0 0 0]]
<class 'numpy.ndarray'>
(10000, 1)
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/080001.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/080002.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/080003.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/080004.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/080005.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/080006.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/080007.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/080008.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/relea

In [11]:
idx = 'test_label'
#print(data[idx])
print(type(data[idx]))
print(data[idx].shape)
test_label = data[idx]
print(test_label)

idx = 'test_images_name'
#print(data[idx])
print(type(data[idx]))
print(data[idx].shape)
#print(data[idx])
test_images_name = []
for i in range(len(data[idx])):
    test_images_name.append("/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/"+str(data[idx][i][0][0]))
    if i <= 10:
        print(test_images_name[i])
#print(train_images_name)

<class 'numpy.ndarray'>
(10000, 26)
[[0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]]
<class 'numpy.ndarray'>
(10000, 1)
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/090001.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/090002.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/090003.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/090004.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/090005.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/090006.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/090007.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/release_data/090008.jpg
/home/anhaoran/data/pedestrian_attributes_PA-100K/data/release_data/relea

In [12]:
import numpy as np

all_images = np.vstack((np.asarray(train_images_name).reshape((-1,1)),
                        np.asarray(val_images_name).reshape((-1,1)),
                        np.asarray(test_images_name).reshape((-1,1))))
print(all_images.shape)
all_attributes = np.vstack((np.asarray(train_label),
                        np.asarray(val_label),
                        np.asarray(test_label)))
print(all_attributes.shape)
all_data = np.hstack((np.asarray(all_images).reshape((-1, 1)), np.asarray(all_attributes)))
print(all_data.shape)

(100000, 1)
(100000, 26)
(100000, 27)


In [13]:
import pandas as pd

attributes_pd = pd.DataFrame(all_data)
attributes_pd

0  1  2  3  4  5  6  7   \
0      /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  1  0  0   
1      /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
2      /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  1  0   
3      /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
4      /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  1  0   
5      /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  0  1  0  0  1   
6      /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
7      /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  0  1   
8      /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
9      /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
10     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  0  1  1  0  0   
11     /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  1  0  0   
12     /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  0  1   
13     /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  1  0   
14     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
15     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
16     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
17     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  1  0   
18     /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  1  0   
19     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
20     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
21     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
22     /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  0  1  1  0  0   
23     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
24     /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  0  1   
25     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  1  0   
26     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  1  0   
27     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
28     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
29     /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  1  0   
...                                                  ... .. .. .. .. .. .. ..   
99970  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  0  1   
99971  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
99972  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  1  0   
99973  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  0  1   
99974  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  1  0   
99975  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  1  0   
99976  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
99977  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  1  0   
99978  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
99979  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
99980  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  0  1   
99981  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
99982  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  0  1  0   
99983  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  1  0  0  1  0  0   
99984  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  1  0   
99985  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  0  1   
99986  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1  0  1  0  0   
99987  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1  0  0  1  0   
9998

In [14]:
attributes_pd.to_csv("../results/PA-100K_labels_pd.csv")
data_read = pd.read_csv("../results/PA-100K_labels_pd.csv")
data_read

Unnamed: 0                                                  0  1  2  3  \
0               0  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
1               1  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
2               2  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
3               3  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
4               4  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
5               5  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  0   
6               6  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
7               7  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
8               8  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
9               9  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
10             10  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  0   
11             11  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
12             12  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
13             13  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
14             14  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
15             15  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
16             16  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
17             17  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
18             18  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
19             19  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
20             20  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
21             21  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
22             22  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  0   
23             23  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
24             24  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
25             25  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
26             26  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
27             27  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
28             28  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
29             29  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
...           ...                                                ... .. .. ..   
99970       99970  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
99971       99971  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99972       99972  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
99973       99973  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99974       99974  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99975       99975  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99976       99976  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99977       99977  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99978       99978  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99979       99979  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99980       99980  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
99981       99981  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99982       99982  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99983       99983  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  1  0   
99984       99984  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
99985       99985  /home/anhaoran/data/pedestrian_attributes_PA-1...  1  0  1   
99986       99986  /home/anhaoran/data/pedestrian_attributes_PA-1...  0  0  1   
99987       99987  /home/anhaoran/data

# Attributes

In [15]:
for i in range(len(attributes_list)):
    print(i, ': ', attributes_list[i])

0 :  Female
1 :  AgeOver60
2 :  Age18-60
3 :  AgeLess18
4 :  Front
5 :  Side
6 :  Back
7 :  Hat
8 :  Glasses
9 :  HandBag
10 :  ShoulderBag
11 :  Backpack
12 :  HoldObjectsInFront
13 :  ShortSleeve
14 :  LongSleeve
15 :  UpperStride
16 :  UpperLogo
17 :  UpperPlaid
18 :  UpperSplice
19 :  LowerStripe
20 :  LowerPattern
21 :  LongCoat
22 :  Trousers
23 :  Shorts
24 :  Skirt&Dress
25 :  boots


In [ ]:
low_level = [15,16,17,18,19,20]
mid_level = [7,8,9,10,11,12,13,14,21,22,23,24,25]
high_level = [0,1,2,3,4,5,6]