In [2]:
from keras.preprocessing import image
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, roc_curve, recall_score, auc, roc_auc_score

low_level = [1]
mid_level = [2,3,4,5,6,7,8]
high_level = [0]
filename = r"../results/berk-test.csv"
data = np.array(pd.read_csv(filename))[:, 1:]
length = len(data)
data_x = np.zeros((length, 420, 210, 3))
data_y = np.zeros((length, 9))
for i in range(length):
    #img = image.load_img(path + m)
    img = image.load_img(data[i, 0], target_size=(420, 210, 3))
    data_x[i] = image.img_to_array(img)
    data_y[i] = np.array(data[i, 1:10], dtype="float32")
data_y_hiar = data_y[:, list(np.hstack((low_level, mid_level, high_level)))]
X_test = data_x
y_test = data_y
y_test_hiar = data_y_hiar
print("The shape of the X_test is: ", X_test.shape)
print("The shape of the y_test is: ", y_test.shape)
print("The shape of the y_test is: ", y_test_hiar.shape)

The shape of the X_test is:  (4001, 420, 210, 3)
The shape of the y_test is:  (4001, 9)
The shape of the y_test is:  (4001, 9)


In [3]:
!ls ../results

1.jpg
berk.csv
berk-test.csv
GoogLeNet_binary61_feature_imagenet_all.npy
GoogLeNet_binary61_feature_imagenet_test7600.npy
googlenet_weights.npy
logs
metrics
models
OEDCWPAL_PETA_features_all.pickle
PETA_coarse_to_fine_labels_pd.csv
PETA.csv
PETA_labels_pd.csv
PETA_lowerBody_labels_pd.csv
PETA_ratio_positive_samples_for_attributes.json
predictions
relation_array.npy
samples
state_transition_matrix.npy


In [4]:
attributes_list = ['is_male', 'has_long_hair', 'has_glasses', 'has_hat', 'has_t-shirt', 'has_long_sleeves', 'has_shorts', 'has_jeans', 'has_long_pants']
predictions_prob = np.load("../results/predictions/GoogLeNet_binary9-depth9_predictions_imagenet_berk.npy")
predictions = np.array(predictions_prob >= 0.5, dtype="float64")
label = y_test

print(predictions)
print(label)

for i in range(label.shape[1]):
    print(attributes_list[i], end=":")
    print(accuracy_score(predictions[:, i], label[:, i]))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [1. 0. 1. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 1.]]
is_male:0.5851037240689827
has_long_hair:0.8145463634091478
has_glasses:0.8572856785803549
has_hat:0.8647838040489878
has_t-shirt:0.8742814296425894
has_long_sleeves:0.6328417895526118
has_shorts:0.9465133716570857
has_jeans:0.9077730567358161
has_long_pants:0.7313171707073232


In [7]:
attributes_list_hiar = list(np.array(attributes_list)[list(np.hstack((low_level, mid_level, high_level)))])
predictions_prob = np.load("../results/predictions/hiarBayesGoogLeNet_binary9_predictions500_imagenet_berk.npy")
predictions = np.array(predictions_prob >= 0.5, dtype="float64")
label = y_test_hiar
610
print(predictions)
print(label)

for i in range(label.shape[1]):
    print(attributes_list_hiar[i], end=":")
    print(accuracy_score(predictions[:, i], label[:, i]))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 1. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 1. 1. 0.]]
has_long_hair:0.7595601099725069
has_glasses:0.786303424143964
has_hat:0.8675331167208198
has_t-shirt:0.849787553111722
has_long_sleeves:0.6778305423644089
has_shorts:0.9432641839540115
has_jeans:0.8960259935016246
has_long_pants:0.7488127968007998
is_male:0.6003499125218695
